[2018-06-15 08:16:43] fast-d.ERROR: handle exception {"msg":"handle exception","code":0,"file":"/Users/janhuang/Documents/htdocs/me/fastd/fastd/tests/NotDBTest.php","line":70,"trace":["#0 [internal function]: NotDBTest->testHandleException()","#1 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(910): ReflectionMethod->invokeArgs(Object(NotDBTest), Array)","#2 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(770): PHPUnit_Framework_TestCase->runTest()","#3 phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php(685): PHPUnit_Framework_TestCase->runBare()","#4 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(726): PHPUnit_Framework_TestResult->run(Object(NotDBTest))","#5 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(747): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))","#6 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(747): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))","#7 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(747): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))","#8 phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php(429): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))","#9 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(155): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)","#10 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(106): PHPUnit_TextUI_Command->run(Array, true)","#11 /usr/local/bin/phpunit(514): PHPUnit_TextUI_Command::main()","#12 {main}"]} []
